# Generated by Django 4.2.8 on 2024-01-02 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionapp', '0002_alter_testattempt_test_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
