# Generated by Django 4.2.8 on 2024-01-02 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionapp', '0003_alter_question_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='testattempt',
            name='timetaken',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='total_questions',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='total_right',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='total_wrong',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
