# Generated by Django 4.2.8 on 2024-01-03 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionapp', '0004_testattempt_timetaken_testattempt_total_questions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testattempt',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='testattempt',
            name='timetaken',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
