# Generated by Django 5.0 on 2024-01-30 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionapp', '0006_alter_userquestionattempt_time_taken'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='test',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'DRAFT'), ('LIVE', 'LIVE')], default='DRAFT', max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='questionapp.subject'),
        ),
    ]
